require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Layout/LineLength:
  Max: 130
  Exclude:
    - app/controllers/rewards_controller.rb
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
      - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
      - spec/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/LetSetup:
  Exclude:
    - spec/system/* 

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
